### ISSUE TITLE
mute button resets after level change

### ISSUE THREAD

**Issue by ZainMahmoodC** [clgzb9610/planets-wekazaji#16]
If you die with the sound mute, the sound stays mute but the level reset changes the dashboard to have the initial(nonMute) frame. If you click on it, the sound stays mute but the animation frame changes to the right one (it remutes the sound basically).

**Comment by kaylabeckm** [comment]
added a boolean check in addDashboard to check if things are muted. also jin changed mute to a button instead of a sprite so it works more reliably now.
