### ISSUE TITLE
Making the enemy better

### ISSUE THREAD

**Issue by ZainMahmoodC** [clgzb9610/planets-wekazaji#2]
-Stop enemy colliding with gears
-smoothen enemycontactcallback
-Figure out how to better change the velocity after collision (Contact.log(enemyVelocity))
-Use enemyGroup so that we can declare enemies in the level design

Ideas:

-If the player jumps on top of the enemy, it kills it.

**Comment by kaylabeckm** [comment]
I fixed collision with the gears. If you pull the declaration of enemies into a function, and copy the level declarations of the other things in the level writeups, the fourth one will be done also.
